### ISSUE TITLE
CalledProcessError on installation of pre-commit 

### ISSUE THREAD

**Issue by Roald87** [pre-commit/mirrors-prettier#18]
I've added the following lines to my `.pre-commit-config.yml:

```yml
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
```

On running ``pre-commit` I get the following error:

```
❯ pre-commit
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:

    up to date, audited 1 package in 1s

    found 0 vulnerabilities

stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.

Check the log at C:\Users\roald\.cache\pre-commit\pre-commit.log
```

I've found similar errors and tried those solutions, but they didn't work. So far I've tried:
- Using different repos as suggested [here](https://github.com/prettier/prettier/issues/9459).
- Tried different version tags
- [Downgraded virtualenv](https://stackoverflow.com/questions/65192345/calledprocesserror-with-git-pre-commit-hook)
- [Changing the git filename length](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows/22575737#22575737)
- Upgrading npm to the latest version

Any other ideas?

**Comment by asottile** [comment]
that seems kinda weird -- you can probably reproduce the same error without pre-commit by running the following -- what does this give you?

```bash
git clone https://github.com/pre-commit/mirrors-prettier
cd mirrors-prettier
nodeenv nenv
. nenv/bin/activate
npm install --dev --prod --ignore-prepublish --no-progress --no-save
echo $?
```

given I don't see any error message in the output, I'm inclined to believe something fishy with `npm` in general on your host -- do you have any special npm configuration set up?

also please post the error log file, it has important information that's necessary for diagnosis

**Comment by Roald87** [comment]
> what does this give you?

```
❯ . .\nenv\Scripts\activate.bat
❯ npm install --dev --prod --ignore-prepublish --no-progress --no-save
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm WARN placeholder_package@0.0.0 No repository field.
npm WARN placeholder_package@0.0.0 No license field.

up to date in 0.405s
found 0 vulnerabilities

❯ echo $?
True
```

>  do you have any special npm configuration set up?

Possibly. npm was installed when I installed the web development tools of visual studio 2017.

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.26.1.windows.1
sys.version:
    3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\roald\miniconda3\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:
    
    up to date, audited 1 package in 1s
    
    found 0 vulnerabilities
    
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    
```

```
Traceback (most recent call last):
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\error_handler.py", line 70, in error_handler
    yield
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\main.py", line 396, in main
    return run(args.config, store, args)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\commands\run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\languages\node.py", line 107, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\languages\helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout:
    
    up to date, audited 1 package in 1s
    
    found 0 vulnerabilities
    
stderr:
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
```

**Comment by asottile** [comment]
what shell are you using?

**Comment by Roald87** [comment]
Windows Terminal/Powershell

**Comment by asottile** [comment]
how about:
```bash
git clone https://github.com/pre-commit/mirrors-prettier
cd mirrors-prettier
nodeenv nenv
. nenv\Scripts\activate
nenv\Scripts\npm.CMD install --dev --prod --ignore-prepublish --no-progress --no-save
echo $?
```

sorry assumed the wrong shell

**Comment by Roald87** [comment]
```
 roald: Downloads ❯ git clone https://github.com/pre-commit/mirrors-prettier
fatal: destination path 'mirrors-prettier' already exists and is not an empty directory.
 roald: Downloads ❯ cd mirrors-prettier
 roald: mirrors-prettier on master [ 10.6.0] ❯ nodeenv nenv
 * Environment already exists: nenv
 roald: mirrors-prettier on master [ 10.6.0] ❯ . nenv\Scripts\activate
(nenv)  roald: mirrors-prettier on master [ 17.7.2] ❯ nenv\Scripts\npm.CMD install --dev --prod --ignore-prepublish --no-progress --no-save
npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.

up to date, audited 1 package in 2s

found 0 vulnerabilities
(nenv)  roald: mirrors-prettier on master [ 17.7.2] ❯ echo $?
True
```

**Comment by asottile** [comment]
please start over from scratch, obviously don't keep the previous junk around

**Comment by Roald87** [comment]
I tried it with both normal and admin privileges, but both times it gives an error: `Error: Failed to create nodejs.exe link`.

Without admin I got 

```
You do not have sufficient privilege to perform this operation.
You do not have sufficient privilege to perform this operation.
Error: Failed to create nodejs.exe link
```

Below the full output with admin privileges:

```
 roald: system32 ❯ git clone https://github.com/pre-commit/mirrors-prettier
cd mirrors-prettier
nodeenv nenv
. nenv\Scripts\activate
nenv\Scripts\npm.CMD install --dev --prod --ignore-prepublish --no-progress --no-save
echo $?
Cloning into 'mirrors-prettier'...
remote: Enumerating objects: 475, done.
remote: Counting objects: 100% (475/475), done.
remote: Compressing objects: 100% (57/57), done.
Receiving objec75 (delta 324), reused 447 (delta 302), pack-reused 0R
Receiving objects: 100% (475/475), 33.61 KiB | 1.29 MiB/s, done.
Resolving deltas: 100% (324/324), done.
 * Install prebuilt node (17.7.2) ..... done.
symbolic link created for nenv\Scripts\nodejs.exe <<===>> node.exe
symbolic link created for nenv\Scripts\nodejs.exe <<===>> node.exe
Error: Failed to create nodejs.exe link
npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.

up to date, audited 1 package in 1s

found 0 vulnerabilities
True
```

**Comment by asottile** [comment]
do you have any of these environment variables set?

https://github.com/pre-commit/pre-commit/blob/4421cb942485d0122e7a39d51b9f034366994145/pre_commit/languages/node.py#L57-L63

**Comment by Roald87** [comment]
None except `PATH`:

```
>  $env:path -split ";"
C:\Program Files\ImageMagick-7.0.11-Q16-HDRI
C:\TwinCAT\Common64
C:\TwinCAT\Common32
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Git\cmd
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\
C:\ProgramData\chocolatey\bin
C:\Users\roald\miniconda3
C:\Users\roald\miniconda3\Library\mingw-w64\bin
C:\Users\roald\miniconda3\Library\usr\bin
C:\Users\roald\miniconda3\Library\bin
C:\Users\roald\miniconda3\Scripts
C:\Ruby27-x64\bin
C:\Users\roald\AppData\Local\Microsoft\WindowsApps
C:\Program Files (x86)\GitHub CLI\
C:\Users\roald\.dotnet\tools
C:\Program Files\nuget
C:\Users\roald\AppData\Local\Programs\oh-my-posh\bin
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\NodeJs
```

I also tried to run your suggested commands again in admin powershell after removing the last path (`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\NodeJs`), but the result was the same.

**Comment by asottile** [comment]
yeah the weird thing is your commands in the terminal are the same as what pre-commit runs but the last one returns a different code for some reason

**Comment by Roald87** [comment]
Ah so the True at the end is exit code 0? The `Error: Failed to create nodejs.exe link` is not bad? 

Btw when I google on `Error: Failed to create nodejs.exe link` I just a few results and they [involve](https://github.com/ekalinin/nodeenv/issues/190) [you](https://github.com/ekalinin/nodeenv/issues/243). x)

**Comment by asottile** [comment]
yeah that's just a warning that can be completely ignored

**Comment by Roald87** [comment]
I added `--verbose` to the npm subprocess call

https://github.com/pre-commit/pre-commit/blob/84372e0edc7f5ac08361a10bcd312bc80dd20960/pre_commit/languages/node.py#L104

Not sure if it is useful. I do not see anything special. But the npm exit codes there are 0.

### version information

```
pre-commit version: 2.17.0
git --version: git version 2.26.1.windows.1
sys.version:
    3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\roald\miniconda3\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save', '--verbose')
return code: 1
expected return code: 0
stdout:
    
    up to date, audited 1 package in 2s
    
    found 0 vulnerabilities
    
stderr:
    npm verb cli [
    npm verb cli   'C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\node.exe',
    npm verb cli   'C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\node_modules\\npm\\bin\\npm-cli.js',
    npm verb cli   'install',
    npm verb cli   '--dev',
    npm verb cli   '--prod',
    npm verb cli   '--ignore-prepublish',
    npm verb cli   '--no-progress',
    npm verb cli   '--no-save',
    npm verb cli   '--verbose'
    npm verb cli ]
    npm info using npm@8.5.2
    npm info using node@v17.7.2
    npm timing npm:load:whichnode Completed in 0ms
    npm timing config:load:defaults Completed in 3ms
    npm timing config:load:file:C:\Users\roald\.cache\pre-commit\repob8x7g6fm\node_env-default\Scripts\node_modules\npm\npmrc Completed in 1ms
    npm timing config:load:builtin Completed in 2ms
    npm verb config dev Please use --include=dev instead.
    npm verb config production Use `--omit=dev` instead.
    npm timing config:load:cli Completed in 4ms
    npm timing config:load:env Completed in 1ms
    npm timing config:load:file:C:\Users\roald\.cache\pre-commit\repob8x7g6fm\.npmrc Completed in 0ms
    npm timing config:load:project Completed in 12ms
    npm timing config:load:file:C:\Users\roald\.npmrc Completed in 0ms
    npm timing config:load:user Completed in 0ms
    npm timing config:load:file:C:\Users\roald\.cache\pre-commit\repob8x7g6fm\node_env-default\Scripts\etc\npmrc Completed in 1ms
    npm timing config:load:global Completed in 1ms
    npm timing config:load:validate Completed in 0ms
    npm timing config:load:credentials Completed in 2ms
    npm timing config:load:setEnvs Completed in 1ms
    npm timing config:load Completed in 26ms
    npm timing npm:load:configload Completed in 26ms
    npm timing npm:load:setTitle Completed in 0ms
    npm timing config:load:flatten Completed in 5ms
    npm timing npm:load:display Completed in 10ms
    npm verb logfile C:\Users\roald\AppData\Local\npm-cache\_logs\2022-03-21T18_29_13_885Z-debug-0.log
    npm timing npm:load:logFile Completed in 34ms
    npm timing npm:load:timers Completed in 0ms
    npm timing npm:load:configScope Completed in 0ms
    npm timing npm:load Completed in 73ms
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm timing arborist:ctor Completed in 2ms
    npm timing arborist:ctor Completed in 0ms
    npm timing idealTree:init Completed in 21ms
    npm timing idealTree:userRequests Completed in 1ms
    npm timing idealTree:#root Completed in 1ms
    npm timing idealTree:buildDeps Completed in 3ms
    npm timing idealTree:fixDepFlags Completed in 0ms
    npm timing idealTree Completed in 28ms
    npm timing reify:loadTrees Completed in 29ms
    npm timing reify:diffTrees Completed in 2ms
    npm timing reify:retireShallow Completed in 1ms
    npm timing reify:createSparse Completed in 0ms
    npm timing reify:loadBundles Completed in 0ms
    npm timing reify:audit Completed in 0ms
    npm timing reify:unpack Completed in 0ms
    npm timing reify:unretire Completed in 0ms
    npm timing build:queue Completed in 0ms
    npm timing build:deps Completed in 1ms
    npm timing build Completed in 1ms
    npm timing reify:build Completed in 1ms
    npm timing reify:trash Completed in 0ms
    npm timing reify Completed in 48ms
    npm timing command:install Completed in 61ms
    npm verb exit 0
    npm timing npm Completed in 1642ms
    npm info ok 
    
```

```
Traceback (most recent call last):
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\error_handler.py", line 70, in error_handler
    yield
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\main.py", line 396, in main
    return run(args.config, store, args)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\commands\run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\repository.py", line 82, in _hook_install
    lang.install_environment(
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\languages\node.py", line 107, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\languages\helpers.py", line 52, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\roald\miniconda3\lib\site-packages\pre_commit\util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save', '--verbose')
return code: 1
expected return code: 0
stdout:
    
    up to date, audited 1 package in 2s
    
    found 0 vulnerabilities
    
stderr:
    npm verb cli [
    npm verb cli   'C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\node.exe',
    npm verb cli   'C:\\Users\\roald\\.cache\\pre-commit\\repob8x7g6fm\\node_env-default\\Scripts\\node_modules\\npm\\bin\\npm-cli.js',
    npm verb cli   'install',
    npm verb cli   '--dev',
    npm verb cli   '--prod',
    npm verb cli   '--ignore-prepublish',
    npm verb cli   '--no-progress',
    npm verb cli   '--no-save',
    npm verb cli   '--verbose'
    npm verb cli ]
    npm info using npm@8.5.2
    npm info using node@v17.7.2
    npm timing npm:load:whichnode Completed in 0ms
    npm timing config:load:defaults Completed in 3ms
    npm timing config:load:file:C:\Users\roald\.cache\pre-commit\repob8x7g6fm\node_env-default\Scripts\node_modules\npm\npmrc Completed in 1ms
    npm timing config:load:builtin Completed in 2ms
    npm verb config dev Please use --include=dev instead.
    npm verb config production Use `--omit=dev` instead.
    npm timing config:load:cli Completed in 4ms
    npm timing config:load:env Completed in 1ms
    npm timing config:load:file:C:\Users\roald\.cache\pre-commit\repob8x7g6fm\.npmrc Completed in 0ms
    npm timing config:load:project Completed in 12ms
    npm timing config:load:file:C:\Users\roald\.npmrc Completed in 0ms
    npm timing config:load:user Completed in 0ms
    npm timing config:load:file:C:\Users\roald\.cache\pre-commit\repob8x7g6fm\node_env-default\Scripts\etc\npmrc Completed in 1ms
    npm timing config:load:global Completed in 1ms
    npm timing config:load:validate Completed in 0ms
    npm timing config:load:credentials Completed in 2ms
    npm timing config:load:setEnvs Completed in 1ms
    npm timing config:load Completed in 26ms
    npm timing npm:load:configload Completed in 26ms
    npm timing npm:load:setTitle Completed in 0ms
    npm timing config:load:flatten Completed in 5ms
    npm timing npm:load:display Completed in 10ms
    npm verb logfile C:\Users\roald\AppData\Local\npm-cache\_logs\2022-03-21T18_29_13_885Z-debug-0.log
    npm timing npm:load:logFile Completed in 34ms
    npm timing npm:load:timers Completed in 0ms
    npm timing npm:load:configScope Completed in 0ms
    npm timing npm:load Completed in 73ms
    npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
    npm timing arborist:ctor Completed in 2ms
    npm timing arborist:ctor Completed in 0ms
    npm timing idealTree:init Completed in 21ms
    npm timing idealTree:userRequests Completed in 1ms
    npm timing idealTree:#root Completed in 1ms
    npm timing idealTree:buildDeps Completed in 3ms
    npm timing idealTree:fixDepFlags Completed in 0ms
    npm timing idealTree Completed in 28ms
    npm timing reify:loadTrees Completed in 29ms
    npm timing reify:diffTrees Completed in 2ms
    npm timing reify:retireShallow Completed in 1ms
    npm timing reify:createSparse Completed in 0ms
    npm timing reify:loadBundles Completed in 0ms
    npm timing reify:audit Completed in 0ms
    npm timing reify:unpack Completed in 0ms
    npm timing reify:unretire Completed in 0ms
    npm timing build:queue Completed in 0ms
    npm timing build:deps Completed in 1ms
    npm timing build Completed in 1ms
    npm timing reify:build Completed in 1ms
    npm timing reify:trash Completed in 0ms
    npm timing reify Completed in 48ms
    npm timing command:install Completed in 61ms
    npm verb exit 0
    npm timing npm Completed in 1642ms
    npm info ok
```

**Comment by asottile** [comment]
maybe something on your machine is causing `cmd.exe` to exit nonzero even though it shouldn't be?

**Comment by Roald87** [comment]
I just tested it with a simple script and it returns the expected error codes when run from powershell. I also ran it via Python's `subprocess` and the error codes were the same.

**Comment by Roald87** [comment]
Just tried it with a normal Python installation and it again returned with error code 1.

**Comment by janbaykara** [comment]
Possibly similar error here?

- macOS Monterey 12.0.1 (21A559)
- pre-commit 2.17.0
- git version 2.32.0 (Apple Git-132)

```
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/jan/.cache/pre-commit/repov39q9c5y/node_env-system/bin/node', '/usr/local/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: -6
expected return code: 0
stdout: (none)
stderr:
    dyld[58257]: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib
      Referenced from: /usr/local/Cellar/node/14.12.0/bin/node
      Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.67.dylib' (no such file), '/usr/local/lib/libicui18n.67.dylib' (no such file), '/usr/lib/libicui18n.67.dylib' (no such file), '/usr/local/Cellar/icu4c/70.1/lib/libicui18n.67.dylib' (no such file), '/usr/local/lib/libicui18n.67.dylib' (no such file), '/usr/lib/libicui18n.67.dylib' (no such file)
    
Check the log at /Users/jan/.cache/pre-commit/pre-commit.log
```

**Comment by frojasg1** [comment]
I do not know if that error is unrelated or not, but the same happens to me ...

![image](https://user-images.githubusercontent.com/19916620/166128759-1e60645d-4efd-476d-875b-9cf86bf67c8c.png)

after having had the same uninstallation exception.

I have quite little experience with all of these applications, so this problem totally stops me

**Comment by asottile** [comment]
perhaps this was the problem? https://github.com/pre-commit/pre-commit/issues/2402#issuecomment-1133662353

**Comment by Roald87** [comment]
omg....

After removing `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun` it works. 🥳 

Thanks for keeping this in mind!

**Comment by asottile** [comment]
my only guess is this is your only js-based hook

**Comment by Alexander-Serov** [comment]
> my only guess is this is your only js-based hook

Here is my list of hooks:
```
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-isort
      - id: nbqa-black
        args: [--safe, --quiet]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: pretty-format-json
        files: ^(tests/pv_surprod/|edfsf/insight/config/pv-surprod-for-production/)
        types: [json]
        args: [--autofix]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-ast
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==21.4.3]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args: ["-sn", "-rn"]
        types: [python]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.3.2
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        description: "Checks the style of Markdown/CommonMark files."
        entry: markdownlint-cli2-fix
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        exclude: docs/
```
Is it the only js-based?

**Comment by Alexander-Serov** [comment]
For future users (including me) stumbling on this page, this is a conda-related issue. The main symptom is
```
prettier.................................................................Failed
- hook id: prettier
- duration: 0.03s
- exit code: 1

& was unexpected at this time.
& was unexpected at this time.
& was unexpected at this time.
& was unexpected at this time.
& was unexpected at this time.
& was unexpected at this time.
& was unexpected at this time.
& was unexpected at this time.
```
Google didn't come up with anything useful, so I am publishing it here.
