### ISSUE TITLE
Incompatibile with node v18.0.0

### ISSUE THREAD

**Issue by tim-schilling** [pre-commit/mirrors-prettier#23]
I tried to install pre-commit on an ubuntu 20 machine:

```
pre-commit version: 2.18.1
git --version: git version 2.17.1
sys.version:
    3.9.9 (main, Dec  6 2021, 13:32:56) 
    [GCC 7.5.0]
sys.executable: /home/schillingt/.pyenv/versions/3.9.9/bin/python3.9
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/node', '/home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    /home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/node)
    
```

```
Traceback (most recent call last):
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/main.py", line 371, in main
    return run(args.config, store, args)
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/repository.py", line 221, in install_hook_envs
    _hook_install(hook)
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/languages/node.py", line 108, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/languages/helpers.py", line 51, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/schillingt/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/node', '/home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    /home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/schillingt/.cache/pre-commit/repo8f8mb3zl/node_env-default/bin/node)
```

I went through the flow defined in #18, [here](https://github.com/pre-commit/mirrors-prettier/issues/18#issuecomment-1073066423). That gave me the same `GLIBC_22.28` missing error. Changing the command to install node v17 resolved the issue for the test workflow.

Is it possible to pin this repo temporarily to <18 or !=18.0.0 for node?

**Comment by asottile** [comment]
this isn't a problem with mirrors-prettier -- node has decided you must have a modern glibc for node 18 -- your OS is old -- see #22
