### ISSUE TITLE
be a better open source user and search the issue tracker before creating duplicate issues

### ISSUE THREAD

**Issue by edmundsj** [pre-commit/mirrors-prettier#36]
be a better open source user and search the issue tracker before creating duplicate issues

_Originally posted by @asottile in https://github.com/pre-commit/mirrors-prettier/issues/33#issuecomment-1366744994_
            
I've been searching for a solution to this specific issue in the "closed issues" for some time now and have not been able to figure it out. If you can point to an issue where the solution is I would be tremendously grateful. Not specifying *any* version works, but I can't tell what the version actually installed is, and it's not supported `pre-commit` behavior. I am trying to install version 2.8.3. I do not want to install the alpha 3.0.0. From looking at previous issues, it looks like this [may not be supported](https://github.com/pre-commit/mirrors-prettier/issues/29). If this is the case, please just say so. Seems mind-boggling that this would be the default behavior, as this makes it infeasible to use in conjunction with CI pipelines. Perhaps the implementation of other behavior is just extremely difficult. I don't know.

What I've tried most recently:
```
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 2.8.3
    hooks:
      - id: prettier
        files: '\.(jsx?|tsx?|css)$'
        additional_dependencies:
          - prettier@2.8.3
```
the error:
```
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '2.8.3')
return code: 1
stdout: (none)
stderr:
    error: pathspec '2.8.3' did not match any file(s) known to git
    
Check the log at /home/jordan/.cache/pre-commit/pre-commit.log
```

the output from the logfile:
```
### version information

```
pre-commit version: 2.21.0
git --version: git version 2.34.1
sys.version:
    3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
sys.executable: /home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/python
os.name: posix
sys.platform: linux

### error information
An unexpected error has occurred: CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '2.8.3')
return code: 1
stdout: (none)
stderr:
    error: pathspec '2.8.3' did not match any file(s) known to git
    

Traceback (most recent call last):
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 182, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 164, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/util.py", line 143, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/lib/git-core/git', '-c', 'protocol.version=2', 'fetch', 'origin', '2.8.3', '--depth=1')
return code: 128
stdout: (none)
stderr:
    fatal: couldn't find remote ref 2.8.3
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/main.py", line 366, in main
    return hook_impl(
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/commands/hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/commands/run.py", line 411, in run
    for hook in all_hooks(config, store)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/repository.py", line 227, in all_hooks
    return tuple(
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/repository.py", line 230, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/repository.py", line 205, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/repository.py", line 171, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 186, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 143, in _new_repo
    make_strategy(directory)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 184, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 157, in _complete_clone
    git_cmd('checkout', ref)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/store.py", line 179, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/jordan/.cache/pre-commit-zipapp/Lhw-Ue-PxVSsv69A3F9z4uPfLYi2T3rXWwqXQrWzFqU/wheels/pre_commit-2.21.0-py2.py3-none-any.whl/pre_commit/util.py", line 143, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/lib/git-core/git', 'checkout', '2.8.3')
return code: 1
stdout: (none)
stderr:
    error: pathspec '2.8.3' did not match any file(s) known to git
```

**Comment by edmundsj** [comment]
For those who run into this issue, the fix was marked by the maintainer as "off-topic", and can be found [here](https://github.com/pre-commit/mirrors-prettier/issues/29#issuecomment-1345459525).

**Comment by asottile** [comment]
no, the fix is the one that has thumbs up right above it
